GET http://localhost:5049

###
GET http://localhost:5049/games

###
GET http://localhost:5049/games/4

###
POST http://localhost:5049/games
Content-Type: application/json

{
    "name": "Minecraft",
    "genre": "Kinds & Family",
    "price": 10,
    "releaseDate": "2011-11-18"

}

###
PATCH   http://localhost:5049/games/4
Content-Type: application/json

{
    "name": "Street F mkigther II Turbo",
    "genre": ""
}

###
DELETE http://localhost:5049/games/5
